
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideMenu from "../../public/components/SideMenu";
import styles from "./page.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nevo admin panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
  const currentDate = new Date().toLocaleDateString("en-US", options);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      
      <SideMenu />
      <h3 className={styles.currentDate}>{currentDate}</h3>

      {children}
        
      </body>
    </html>
  );
}
